{{- if .Values.global.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: next-gen-ui
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.global.ingress.objects.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.ingress.objects.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.global.ingress.className | quote }}
  rules:
    {{- range .Values.global.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - backend:
              service:
                name: next-gen-ui
                port:
                  number: 80
            path: /ng(/|$)(.*)
            pathType: ImplementationSpecific
    {{- end }}
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.global.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.global.ingress.tls.secretName }}
  {{- end }}
{{- end }}